### ISSUE TITLE
[GT Desgaste] Revisar relatório de ações futuras

### ISSUE THREAD

**Issue by lfmabr** [jorelanjos/personal#6]
[GT Desgaste] Revisar relatório de ações futuras

**Comment by jorelanjos** [comment]
Eu posso comentar todos os issues

além de que se vc colocar "@" e seu username vc me notifica.

**Comment by lfmabr** [comment]
Eu crio um issue. E onde eu coloco ele em progresso ou terminado?

**Comment by jorelanjos** [comment]
vc arrasta com o mouse
